### ISSUE TITLE
Forge version?

### ISSUE THREAD

**Issue by sk-ed** [Gaider10/BookDupe#2]
I know it's probably a big ask, but can there be a forge version? I am on a modded server which doesn't allow fabric, I tried to port it myself in Eclipse but I really am not great with Forge
A forge version would be really good, the only problem would be that you have to update a forge and a fabric version.
Please consider, thanks!

**Comment by enescglyn** [comment]
which minecraft version?

**Comment by sk-ed** [comment]
1.16

**Comment by enescglyn** [comment]
how did you manage to reply in 1 minute? anyways if it was like 1.12 i would say you could use impact client's forge mod which probably has a book bot that u can just manually tell it to fill with foreign characters but if you are on 1.16 i recommend looking for hacked clients that has a forge mod in 1.16 version

**Comment by feliscatusmeows** [comment]
https://www.curseforge.com/minecraft/mc-mods/branding
happy duping!

**Comment by Gaider10** [comment]
i am not going to make a forge version, i heard that someone was making one, so maybe you can find it somewhere
