### ISSUE TITLE
how does dupe work

### ISSUE THREAD

**Issue by 43ash** [Gaider10/BookDupe#3]
I have found no sources online explaining how this dupe works on a technical level and I have tested replicating the book used for the dupe with the same characters but could not manage to get the book to function or stack with the dupe book. I tried using more or less data but could only achieve a book ban or nothing at all. it would be helpful if someone could explain how this dupe works, thanks.

**Comment by Xicad** [comment]
just click him

**Comment by Gaider10** [comment]
Books in minecraft store their contents using string nbt tags, they have a size limit of 64k bytes, as they use the java short to store their size, and if you create a book with a page over the 64k byte limit, saving the books will cause an exception and prevent your inventory from saving. But there are several things that prevent you from just creating a book with that much data: 1) books have a 32k character limit, but that is quite easy to bypass using 2-byte or 3-byte unicode characters 2) the way books are sent to the server uses the same method as saving them, so there is also the 64k byte limit, so you can't just send a book that big, but there is a way to do it. When the book is processed on the server, all it's text is converted to json. This lets you bypass the 64k limit in 2 ways: 1) when the text is converted to json, some characters are added to it, like {}"", so it you try to create a book that is like 1 byte below the 64k limit, it will be successfully be sent to the server and converted to json, making it over 64k limit, this is what my mod uses 2) you can use some special characters that when converted to json need to be replaced with several characters, like '\n' or '\"', but the best one is '\0', it takes up 2 bytes when sending to the server, but then is replaced with '\u0000', making it 3 times bigger, so if you have for example 30k bytes of '\n', the book will become 90k byte in the end, also going over the 64k limit

**Comment by 43ash** [comment]
thank you this was very helpful.
