### ISSUE TITLE
1.12.2 forge version

### ISSUE THREAD

**Issue by ghost** [Gaider10/BookDupe#5]
Hello, nice mod. It will be interesting if this mod could work on SpongeForge 1.12.2 servers. Can you do it pls?

**Comment by waidesoper** [comment]
Considering the mod is specifically a fabric mod for 1.16 that seems like a lot more work than anyone should reasonably expect.

**Comment by Gaider10** [comment]
I am not going to to make a forge version. And if someone makes it the duping part will work, but it will not regenerate chunks, it will savestate them
