### ISSUE TITLE
1.17pre 4 version crashing

### ISSUE THREAD

**Issue by Redcliff06** [Gaider10/BookDupe#8]
Im using 1.17.1 and using the 1.17pre 4 version idk if i used the wrong mc version or theres something wrong with the pre 4 version since when i type .s in chat it crashes.Thanks

**Comment by Gaider10** [comment]
The bug this mod uses is fixed in 1.17.1

**Comment by Redcliff06** [comment]
o okok thanks for the notify sorry for late response
