### ISSUE TITLE
Kick and failure to regenerate chunk in 1.17.0

### ISSUE THREAD

**Issue by yeahthegoys** [Gaider10/BookDupe#9]
Running this on a vanilla 1.17.0 server, I get kicked the instant I do .s or .d, and when I rejoin the book is gone, and the chunk is the same. Are there more commands? which one am I supposed to use? How can I get it to work correctly?

**Comment by Volkov997** [comment]
iirc this has been patched in 1.17

**Comment by Gaider10** [comment]
you need the book to be in a hopper for the chunk to regenerate in 1.17, so use .s when standing on a hopper looking down, and probably you will need something like a chunkloader loading then chunk so the book has time to enter the hopper
